### ISSUE TITLE
Add performance metrics for the README.md

### ISSUE THREAD

**Issue by afrozchakure** [mesutpiskin/id-card-detector#26]
Things that can be added to the README.md file :
* Add performance metrics for the program.
* Analysis of time and memory space taken while running the model.

**Comment by amashi01** [comment]
getting error

 File "id_card_detection_image.py", line 103, in <module>
    im = Image.open(image_path)
NameError: name 'image_path' is not defined

Replaced image_path with PATH_TO_IMAGE fixed above error

  File "id_card_detection_image.py", line 105, in <module>
    im.crop((left, top, right, bottom)).save(output_path, quality=95)
NameError: name 'output_path' is not defined

define output_path in the code fixed above error

but getting new error not sure where to fix

Traceback (most recent call last):
  File "/Users/amashi/PycharmProjects/claydesk/venv/lib/python3.7/site-packages/PIL/Image.py", line 2082, in save
    format = EXTENSION[ext]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "id_card_detection_image.py", line 106, in <module>
    im.crop((left, top, right, bottom)).save(output_path, quality=95)
  File "/Users/amashi/PycharmProjects/claydesk/venv/lib/python3.7/site-packages/PIL/Image.py", line 2084, in save
    raise ValueError("unknown file extension: {}".format(ext))
ValueError: unknown file extension:

**Comment by amashi01** [comment]
> getting error
> 
> File "id_card_detection_image.py", line 103, in
> im = Image.open(image_path)
> NameError: name 'image_path' is not defined
> 
> Replaced image_path with PATH_TO_IMAGE fixed above error
> 
> File "id_card_detection_image.py", line 105, in
> im.crop((left, top, right, bottom)).save(output_path, quality=95)
> NameError: name 'output_path' is not defined
> 
> define output_path in the code fixed above error
> 
> but getting new error not sure where to fix
> 
> Traceback (most recent call last):
> File "/Users/amashi/PycharmProjects/claydesk/venv/lib/python3.7/site-packages/PIL/Image.py", line 2082, in save
> format = EXTENSION[ext]
> KeyError: ''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "id_card_detection_image.py", line 106, in
> im.crop((left, top, right, bottom)).save(output_path, quality=95)
> File "/Users/amashi/PycharmProjects/claydesk/venv/lib/python3.7/site-packages/PIL/Image.py", line 2084, in save
> raise ValueError("unknown file extension: {}".format(ext))
> ValueError: unknown file extension:

Fixed the error by passing correct output_path
